name: TravelOrDie
favicon: null
layout_spectrum: 0.46014564181677997
typography_spectrum: 0.6011333162896335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.32010804465971887
  lightness: 0.5481264574918896
  saturation: 0.8038182195741683
  rhythmicContrast: 0.9848031501751393
purpose: []
